---

### Initialize
- include: "{{ project_deploy_hook_on_initialize | default(lookup('pipe', 'pwd') ~ '/hooks/example.yml') }}"

- name: Initialize
  deploy_helper: "path={{ project_root }} state=present shared_path={{ project_shared_path }}"


### Update source
- include: "{{ project_deploy_hook_on_update_source | default(lookup('pipe', 'pwd') ~ '/hooks/example.yml') }}"

- name: Clone project files
  git: "repo={{ project_git_repo }} dest={{ project_source_path }} version={{ project_version }}"
  when: project_deploy_strategy == 'git'

- name: Rsync project files
  synchronize: "src={{ project_local_path }} dest={{ project_source_path }} rsync_timeout={{ project_deploy_synchronize_timeout }} delete={{ project_deploy_synchronize_delete }} recursive=yes "
  when: project_deploy_strategy == 'synchronize'

- name: s3 download project files
  s3: "bucket={{ project_s3_bucket }} mode=get object='{{ project_s3_path }}/{{ project_s3_filename }}' dest='{{ project_source_path }}/{{ project_final_filename|default(project_s3_filename) }}' aws_access_key={{ aws_access_key }} aws_secret_key={{ aws_secret_key }} region={{ project_s3_region }}"
  when: project_deploy_strategy == 's3'

- name: write unfinished file
  file: "path={{ project_source_path }}/{{ deploy_helper.unfinished_filename }} state=touch"


### Create build dir
- include: "{{ project_deploy_hook_on_create_build_dir | default(lookup('pipe', 'pwd') ~ '/hooks/example.yml') }}"

- name: Copy files to new build dir
  command: "cp -pr {{ project_source_path }} {{ deploy_helper.new_release_path }}"

- name: Remove unwanted files/folders from new release
  file: "path={{ deploy_helper.new_release_path }}/{{ item }} state=absent"
  with_items: project_unwanted_items

- name: Copy project files
  copy: src={{ item.src }} dest={{ deploy_helper.new_release_path }}/{{ item.dest }} mode={{ item.mode|default('0644') }}
  with_items: project_files

- name: Copy project templates
  template: src={{ item.src }} dest={{ deploy_helper.new_release_path }}/{{ item.dest }} mode={{ item.mode|default('0644') }}
  with_items: project_templates


### Perform build
- include: "{{ project_deploy_hook_on_perform_build | default(lookup('pipe', 'pwd') ~ '/hooks/example.yml') }}"

### Make shared resources
- include: "{{ project_deploy_hook_on_make_shared_resources | default(lookup('pipe', 'pwd') ~ '/hooks/example.yml') }}"

- name: Ensure shared sources are present
  file: "path='{{ deploy_helper.shared_path }}/{{ item.src }}' state={{ item.type|default('directory') }}"
  with_items: project_shared_children

- name: Ensure shared paths are absent
  file: "path='{{ deploy_helper.new_release_path }}/{{ item.path }}' state=absent"
  with_items: project_shared_children

- name: Create shared symlinks
  file: "path='{{ deploy_helper.new_release_path }}/{{ item.path }}' src='{{ deploy_helper.shared_path }}/{{ item.src }}' state=link"
  with_items: project_shared_children


### Finalize
- include: "{{ project_deploy_hook_on_finalize | default(lookup('pipe', 'pwd') ~ '/hooks/example.yml') }}"

- name: Finalize the deploy
  deploy_helper: path={{ project_root }} release={{ deploy_helper.new_release }} state=finalize
  when: project_finalize
